fix(#391): timezones
jakubroztocil/rrule pull request #404
Opened 2020-06-10 05:56 UTC by spurreiter

This fixes the issue described in #391 

rrule time base is UTC whereas Luxon requires dates in local format to
calculate the correct time offset.

New tests where introduced to prove correct behavior in different
system timezones. Run those with `npm run test:tz`

2020-10-28 12:44 UTC, greenreign commented
Any chance to get this merged in?  We've been using the branch and it seemed to fix all our timezone issues.

2021-10-31 14:55 UTC, egarkavy commented
@greenreign May be still actual. I also needed that fix so I published this package to NPM registry with this PR merged
https://www.npmjs.com/package/rrule-community-edition

2021-10-31 21:17 UTC, davidgoli requested changes
I appreciate your PR & the thoughtful work that went into this, but unfortunately, it seems to stem from a fundamental misunderstanding of the API. Please see my comment in the linked issue. Thanks!

2021-10-31 21:17 UTC, davidgoli commented on package.json
> +    "test:tz3": "TZ=America/Chicago npm t"
This project uses `yarn`, please change these to reference `yarn` instead of `npm`

2021-10-31 21:17 UTC, davidgoli commented on test/datewithzone.test.ts
> +    const d = DateTime.fromISO('20101005T110000Z').toJSDate()
The purpose of this test is not to test the ability to use UTC (which already works). It's to test conversion from local time into the expected timezone.

2021-10-31 21:17 UTC, closed without merging